spring:
  application:
    name: cms


  # JPA configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
    hikari:
      maximum-pool-size: 16
      minimum-idle: 8
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_updates: true
        order_inserts: true
        format_sql: true
        generate_statistics: true
        default_schema: postgres

  kafka:
    consumer:
      bootstrap-servers: kafka:9092

    producer:
      bootstrap-servers: kafka:9092
      acks: -1

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    baseline-version: 0
    schemas: postgres

server:
  port: 7070

logging:
  config: classpath:log4j2.yml

  level:
    org:
      apache:
        kafka: WARN
      springframework:
        kafka: WARN

webhook:
  url: ${WEBHOOK_URL}
  secret: ${WEBHOOK_SECRET}

service:
  ams:
    baseUrl: ${AMS_URL}

  client:
    baseUrl: ${CLIENT_URL}